config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'genres/show'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


scope module: :public do
  root to: "homes#top"
  get "customers/about"=>"homes#about"
  get "search" => "searches#search"
  get "customers/mypage" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"
  resources :items,only: [:index,:show] do
    collection do
      get "/search" => "items#search"
    end
  end
  resources :genres, only: [:show]
  resources :cart_items,only: [:index, :update, :destroy, :create] do
    collection do
      delete "destroy_all"
    end
  end
  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post "check"
      get "complete"
    end
  end
  resources :addresses, except: [:show]
end



#管理者側のルーティング設定
namespace :admin do
  get "/" => "homes#top"
  get "search" => "searches#search"
  resources :items,except: [:destroy]
  resources :genres,except:  [:new,:destroy]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :serches, only: [:index]
  resources :orders, only: [:index, :show, :update] do
    member do
      get "individual"
    end
  end
  resources :order_details, only: [:update]
end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * count
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :oder_details

  def item_status
    if is_available == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name","introduction"]
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, check: 1, making: 2, standby: 3, sent: 4 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    # 注文履歴一覧　1ページ当たりの表示数は10
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
  end

end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController

   def update
    @order_detail = OrderDetail.find(params[:id])
    @order = @order_detail.order
    @order_details = @order.order_details
    @order_detail.update(order_detail_params)
    @making_statuses = @order_details.pluck(:making_status)
    @order.update(status: "making") if @making_statuses.any?{|val| val == "making" }
    @order.update(status: "standby") if @making_statuses.all?{|val| val ==  "finish"}

    redirect_to admin_order_path(@order)

    if @order_detail.errors.any?
      flash[:alert] = "製作ステータスが更新できませんでした。"
    else
      flash[:notice] = "製作ステータスを更新しました。"
    end
  end

  private

  def order_detail_params
    params.require(:order_detail).permit(:making_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(10).order("created_at desc")
  end

  def individual
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.page(params[:page]).per(10).order("created_at desc")
  end

  def show
    @order = Order.find(params[:id])
    @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.total_price }
  end

def update
  @order = Order.find(params[:id])
  @order_details = OrderDetail.where(order_id: params[:id])

  if @order.update(order_params) && @order.status == "check"
    @order_details.each do |order_detail|
      order_detail.update(making_status: "wait")
    end
  end

    flash[:notice] = "注文ステータスを更新しました。"
    redirect_to admin_order_path(@order)
  rescue => e
    flash[:alert] = "注文ステータスの更新に失敗しました。"
    redirect_to admin_order_path(@order)
  end


  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :search
  
  def search
    @q = Item.ransack(params[:q])
    @item = @q.result(distinct:true)
    @result = params[:q]&.values&.reject(&:blank?)
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:last_name,
                                             :first_name,
                                             :last_name_kana,
                                             :first_name_kana,
                                             :address,
                                             :postcode,
                                             :phone_number,
                                             :is_deleted
                                             ])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @customer.full_name %>さんの会員情報編集</h4>
      <%= render"layouts/error_messages", obj: @customer %>
      <table class="table table-borderless">
        <%= form_with model: [:admin, @customer] do |f| %>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %>　<%= f.text_field :first_name %></td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana %>　<%= f.text_field :first_name_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postcode %></td>
          <td></td>
        </tr>

        <tr>
          <td>住所</td>
          <td><%= f.text_field :address %></td>
          <td></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :phone_number %></td>
          <td></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", { value: :false }  %>

            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", { value: :true } %>
          </td>
        </tr>

        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class:"btn", style: "background-color: #64CCC5; color: white;" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5">会員一覧</h4>
        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.full_name, admin_customer_path(customer), class: "link" %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == true %>
                <span style="color:darkgray;"><%= "退会" %></strong>
                <% else %>
                <strong style="color:orange;"><%= "有効" %></strong>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @customer.full_name %>さんの会員詳細</h4>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>

          <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>

          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postcode %></td>
          </tr>

          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <th>電話番号</th>
            <td><%= @customer.phone_number %></td>
          </tr>

          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <td><%= @customer.customer_status %></td>
          </tr>

          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_customer_path, class:"btn", style: "background-color: #64CCC5; color: white;" %>
            <%= link_to "注文履歴一覧を見る", individual_admin_order_path(@customer), class: "btn", style: "background-color: #9AC5F4; color: white;" %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/edit.html.erb
      <h2 class="ml-5 my-5">ジャンル編集</h2>
      <%= form_with model: @genre, url: admin_genre_path,method: :patch do |f| %>
        <td><%= f.label :ジャンル名, class: "mr-3 genreedit" %></td>
        <td><%= f.text_field:name, class: "mr-2" %></td>
        <td><%= f.submit "変更を保存", class: "btn", style: "background-color: #64CCC5; color: white; mx-3 mb-5" %></td>
      <% end %>

app/views/admin/genres/index.html.erb
<div class="genre">
  <div class='container'>
    <div class='row'>
      <div class= 'col-md-4'>
        <h4 class ="mr-5 mt-5">ジャンル一覧・追加</h4>
          <div class="row">
            <%=form_with model: @genre,url: admin_genres_path, method: :post do |f| %>
              <p class="genre ml-3">ジャンル名</p>
              <p class="ml-3"><%= f.text_field :name %>
              <%= f.submit '新規登録', class: "btn", style: "background-color: #64CCC5; color: white; mx-3" %>
              <% end %>
              </p>
          </div>
          <div class="genres">
            <div class="d-flex justify-content-center">
              <table class='table table-hover table-inverse'>
                <tr>
                <th class="mr-5">ジャンル</th>
                <th></th>
                </tr>
                <% @genres.each do |genre| %>
                <tr>
                  <td><%= genre.name %></td>
                  <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn", style: "background-color: #64CCC5; color: white; mx-3" %></td>
                  <%end%>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5 admin-order-list">注文履歴一覧</h4>
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id), class: "link" do %>
                <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
              <% end %>
            </td>
            <td><%= order.customer.full_name %></td>
            <td><%= order.order_details.sum(:count) %></td>
            <td><%= order.status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="pagenation mb-3">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <table class="table table-borderless">
        <h4 class="my-4">商品編集</h4>
        <%= form_with model:[:admin, @item] do |f| %>

        <tr>
          <td>商品画像</td>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        
        <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
        </tr>
        
        <tr>
          <td>商品説明</td>
          <td><%= f.text_area :introduction %></td>
        </tr>
        
          <tr>
          <td>ジャンル</td>
          <td><%= f.select :genre_id, @genres,include_blank: "--選択して下さい" %></td>
        </tr>
        
        <tr>
          <td>税抜価格</td>
          <td><%= f.text_field :price %>円</td>
        </tr>
      
        <tr>
          <td>販売ステータス</td>
          <td><%= f.radio_button :is_available, true %>
              <%= f.label :is_available, "販売中" %>
              <%= f.radio_button :is_available, false %>
              <%= f.label :is_available, "販売停止中" %>
           </td>
        </tr>
        
        <tr>
          <td></td>
          <td><%= f.submit '変更を保存', class: "btn", style: "background-color: #64CCC5; color: white; mx-3" %></td>
              <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class='row'>
    <div class="col">
      <h4 class="mt-5">商品一覧</h4>
        <div class="text-right">
          <%= link_to "+", new_admin_item_path, class: "btn", style: "background-color: #64CCC5; color: white; mx-3" %>
        </div>
      <div class="index">
      <table class='table'>
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to admin_item_path(item.id),class: "link" do %>
                <%= item.name %>
                <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_available == true %>
              <strong style="color:orange;"><%= "販売中" %></strong>
              <% else %>
              <span style="color:darkgray;"><%= "停止中" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <table class="table table-borderless">
        <h4 class="mt-3 mb-5">商品新規登録</h4>
        <%= form_with model:[:admin, @item] do |f| %>

        <tr>
          <td>商品画像</td>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>

        <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
        </tr>

        <tr>
          <td>商品説明</td>
          <td><%= f.text_area :introduction %></td>
        </tr>

          <tr>
          <td>ジャンル</td>
          <td><%= f.select :genre_id, @genres,include_blank: "--選択して下さい" %></td>
        </tr>

        <tr>
          <td>税抜価格</td>
          <td><%= f.text_field :price %>円</td>
        </tr>

        <tr>
          <td>販売ステータス</td>
          <td><%= f.radio_button :is_available, true %>
              <%= f.label :is_available, "販売中" %>
              <%= f.radio_button :is_available, false %>
              <%= f.label :is_available, "販売停止中" %>
           </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= f.submit '新規登録', class: "btn", style: "background-color: #64CCC5; color: white; mx-3" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-md-4">
      <h4 class="my-4">商品詳細</h4>
      <%= image_tag @item.image, size: "300x200" %>
    </div>
    <div class="col-md-8 mt-5">
      <table class="table table-borderless">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>

        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>

        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>

        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <td><%= @item.with_tax_price.to_s(:delimited) %>
              (<%= @item.price.to_s(:delimited) %>)
          </td>
        </tr>

        <tr>
          <td>販売ステータス</td>
          <td><%= @item.item_status %></td>
        </tr>

        <tr>
          <td></td>
          <td><%= link_to '編集する',edit_admin_item_path(@item), class: "btn", style: "background-color: #64CCC5; color: white; mx-3" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5 admin-order-list">注文履歴一覧</h4>
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id), class: "link" do %>
                <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
              <% end %>
            </td>
            <td><%= order.customer.full_name %></td>
            <td><%= order.order_details.sum(:count) %></td>
            <td><%= order.status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="pagenation mb-3">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4 class="my-5 admin-individual-show">注文履歴詳細</h4>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer), class: "link" do %>
              <%= @order.customer.full_name %>
            <% end %>
          </td>
        </tr>

        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        </tr>

        <tr>
          <th>配送先</th>
          <td>
            〒<%= @order.postcode %>
            <%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>

        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>

          <tr>
            <th>注文ステータス</th>
            <td>
              <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
               <%= f.select :status, Order.statuses_i18n.invert, {}, class:"form-control col-10" %>
                <%= f.submit '更新', class:"btn col-10", style: "background-color: #64CCC5; color: white;" %>
              <% end %>
            </td>
          </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <table class="table table-bordered">
        <thead class="bg-light table table-borderless">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody class="table table-borderless">
          <% @order.order_details.each do |order_detail| %>
            <tr class="border-bottom">
              <td class="align-middle"><%= order_detail.item.name %></td>
              <td class="align-middle">¥<%= order_detail.tax_price.to_s(:delimited) %></td>
              <td class="align-middle"><%= order_detail.count %></td>
              <td class="align-middle">¥<%= order_detail.total_price.to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |status| [I18n.t("enums.order_detail.making_status.#{status}"), status] }, {}, class: "form-control" %>
                  <%= f.submit '更新', class:"btn form-control", style: "background-color: #64CCC5; color: white;" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td>¥<%= @total.to_s(:delimited) %></td>
        </tr>

        <tr>
          <th>送料</th>
          <td>¥<%= @order.shipping_fee %></td>
        </tr>

        <tr>
          <th>請求金額</th>
          <td>¥<%= @order.total_amount.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg py-4">
    <a>
      <%= link_to root_path, data: { "turbolinks" => false }, class: "mx-4" do %>
        <%= image_tag "logor1.png", alt: "LOGO", size: "90x80" %>
      <% end %>
    </a>

      <%= render 'layouts/search', q: @q %>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mx-5 d-flex ml-auto">
      <% if admin_signed_in? %>
      <li>
        <div class="d-flex justify-content-center align-items-center mr-5">
          <h5 class="mb-0 font-weight-bold">管理者ログイン中</h5>
        </div>
        </li>
      <% end %>

        <% if customer_signed_in? %>
          <li>
            <%= link_to items_path do %>
              <h5>ITEM</h5>
            <% end %>
          </li>

        <% if current_page?(root_path) %>
          <li>
            <div class="category-container ml-3" id="categoryContainer">
              <h5>CATEGORY</h5>
              <div class="category-dropdown" id="categoryDropdown">
                <ul>
                  <li>
                    <% @genres.each do |genre| %>
                　　　　<%= link_to genre.name, genre_path(genre) %>
                　　　<% end %>
                  </li>
                </ul>
              </div>
            </div>
          </li>
        <% end %>

          <li>
            <div class="mypage-btn-container" id="mypageBtnContainer">
              <button class="btn btn-lg mx-3" style="background-color:#FF9494; color: white;"><%= current_customer.full_name %>様</button>
              <div class="mypage-dropdown" id="mypageDropdown">
                <ul>
                  <li><%= link_to 'マイページ', customers_mypage_path %></li>
                  <li><%= link_to '配送先', addresses_path %></li>
                  <li><%= link_to '注文履歴', orders_path %></li>
                  <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>
                </ul>
              </div>
            </div>
          </li>

          <li>
            <%= button_to cart_items_path, method: :get, class: "btn btn-lg mx-3", style: "background-color:#FF9494; color: white;" do %>
              <i class="fas fa-shopping-cart"></i>
            <% end %>
          </li>

        <% elsif admin_signed_in? %>

          <li>
            <%= link_to '商品一覧', admin_items_path, class: "btn mx-3", style: "background-color: #FF9494; color: white;" %>
          </li>

          <li>
            <%= link_to '会員一覧', admin_customers_path, class: "btn mx-3", style: "background-color: #FF9494; color: white;" %>
          </li>

          <li>
            <%= link_to '注文履歴一覧', admin_orders_path, class: "btn mx-3", style: "background-color: #FF9494; color: white;" %>
          </li>

          <li>
            <%= link_to 'ジャンル一覧', admin_genres_path, class: "btn mx-3", style: "background-color: #FF9494; color: white;" %>
          </li>

          <li>
            <%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: "btn mx-3", style: "background-color: #FF9494; color: white;" %>
          </li>

        <% else %>
          <li class="mr-3">
            <%= link_to customers_about_path do %>
              <h5>ABOUT</h5>
            <% end %>
          </li>

          <li class="mr-3">
            <%= link_to items_path do %>
              <h5>ITEM</h5>
            <% end %>
          </li>

          <li>
            <div class="login-btn-container" id="loginBtnContainer">
              <button class="btn btn-lg mx-3" style="background-color:#FF9494; color: white;">LOGIN</button>
              <div class="login-dropdown" id="loginDropdown">
                <ul>
                  <li><%= link_to 'ログイン', new_customer_session_path %></li>
                  <li><%= link_to '新規会員登録', new_customer_registration_path %></li>
                </ul>
              </div>
            </div>
          </li>
        <% end %>

      </ul>

  </nav>
</header>

app/views/layouts/_search.html.erb
<% if controller_name != 'sessions' %>
  <div class="search_box" id="search-box">
    <button class="btn btn-lg search_icon" id="search-icon" style="background-color: #FF9494; color: white;">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
    <div class="search_form pe-3" id="search-form" style="width: 0; direction: rtl;">
      <% @q = Item.ransack %>
      <%= search_form_for @q, url: search_path, class: "row justify-content-end" do |f| %>
        <div class="col-md-8 p-0">
          <%= f.search_field :name_cont, class: "form-control", id: "search-input", placeholder: "商品を検索" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>